### ISSUE TITLE
org.openqa.selenium.WebDriverException: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}

### ISSUE THREAD

**Issue by Eddie1802** [fhoeben/hsac-fitnesse-fixtures#189]
I have updated from version 3.12.0 to 3.15.0 and started to experience the error: "org.openqa.selenium.WebDriverException: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}"

on random times (i.e. not always and not always in the same step) at least once per script. Although mostly on steps that contain 'wait for visible' commands. The scripts seem to run correctly with the errors. I've seen the error thrown on 'click' commands and the element is still being clicked.
I've downgraded to 3.14.1 and still saw the errors, downgrading back to 3.12.0 removes the errors.

Stacktrace (for step:|wait for visible |Submit |):
`org.openqa.selenium.WebDriverException: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
 (Session info: chrome=63.0.3239.132)
 (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MyHost', ip: 'xxx.xx.x.xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.34.522940 (1a76f96f66e3ca..., userDataDir: C:\Users\...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 63.0.3239.132, webStorageEnabled: true}
Session ID: 1d205908736495b7a95eee589b283d09
*** Element info: {Using=css selector, value=input[placeholder*='Submit'],textarea[placeholder*='Submit']}
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
 at java.lang.reflect.Constructor.newInstance(Unknown Source)
 at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
 at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
 at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
 at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
 at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
 at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
 at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:398)
 at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:469)
 at org.openqa.selenium.By$ByCssSelector.findElements(By.java:441)
 at nl.hsac.fitnesse.fixture.util.selenium.by.LazyPatternBy.findElements(LazyPatternBy.java:33)
 at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:359)
 at nl.hsac.fitnesse.fixture.util.selenium.by.BestMatchBy.findElement(BestMatchBy.java:49)
 at nl.hsac.fitnesse.fixture.util.selenium.by.FirstElementBy.getWebElement(FirstElementBy.java:52)
 at nl.hsac.fitnesse.fixture.util.selenium.by.FirstElementBy.lambda$findElement$1(FirstElementBy.java:44)
 at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
 at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
 at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
 at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
 at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
 at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
 at nl.hsac.fitnesse.fixture.util.FirstNonNullHelper.firstNonNull(FirstNonNullHelper.java:98)
 at nl.hsac.fitnesse.fixture.util.FirstNonNullHelper.firstNonNull(FirstNonNullHelper.java:51)
 at nl.hsac.fitnesse.fixture.util.selenium.by.FirstElementBy.findElement(FirstElementBy.java:44)
 at nl.hsac.fitnesse.fixture.util.selenium.by.HeuristicBy.findElement(HeuristicBy.java:39)
 at nl.hsac.fitnesse.fixture.util.selenium.by.FirstElementBy.getWebElement(FirstElementBy.java:50)
 at nl.hsac.fitnesse.fixture.util.selenium.by.FirstElementBy.lambda$findElement$1(FirstElementBy.java:44)
 at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
 at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
 at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
 at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
 at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
 at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
 at nl.hsac.fitnesse.fixture.util.FirstNonNullHelper.firstNonNull(FirstNonNullHelper.java:98)
 at nl.hsac.fitnesse.fixture.util.FirstNonNullHelper.firstNonNull(FirstNonNullHelper.java:51)
 at nl.hsac.fitnesse.fixture.util.selenium.by.FirstElementBy.findElement(FirstElementBy.java:44)
 at nl.hsac.fitnesse.fixture.util.selenium.by.HeuristicBy.findElement(HeuristicBy.java:39)
 at nl.hsac.fitnesse.fixture.util.selenium.by.FirstElementBy.getWebElement(FirstElementBy.java:50)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.findElement(SeleniumHelper.java:939)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.lambda$findElement$2(SeleniumHelper.java:691)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.doInCurrentContext(SeleniumHelper.java:733)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.findElement(SeleniumHelper.java:691)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.lambda$getElementToCheckVisibility$0(SeleniumHelper.java:175)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.findByTechnicalSelectorOr(SeleniumHelper.java:196)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.getElementToCheckVisibility(SeleniumHelper.java:172)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.getElementToCheckVisibility(BrowserTest.java:1617)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.lambda$findByTechnicalSelectorOr$20(BrowserTest.java:2099)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.findByTechnicalSelectorOr(SeleniumHelper.java:196)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.findByTechnicalSelectorOr(BrowserTest.java:2099)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.lambda$getElementToCheckVisibility$18(BrowserTest.java:1621)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.doInContainer(BrowserTest.java:841)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.getElementToCheckVisibility(BrowserTest.java:1621)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitForVisibleIn(BrowserTest.java:985)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitForVisible(BrowserTest.java:978)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:221)
 at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:51)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.superInvoke(BrowserTest.java:135)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.lambda$invokedWrappedInWaitUntil$0(BrowserTest.java:101)
 at nl.hsac.fitnesse.fixture.util.selenium.TryAllFramesConditionDecorator.invokeInFrames(TryAllFramesConditionDecorator.java:46)
 at nl.hsac.fitnesse.fixture.util.selenium.TryAllFramesConditionDecorator.apply(TryAllFramesConditionDecorator.java:35)
 at nl.hsac.fitnesse.fixture.util.selenium.TryAllFramesConditionDecorator.apply(TryAllFramesConditionDecorator.java:16)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.lambda$getConditionIgnoringStaleElement$4(SeleniumHelper.java:901)
 at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
 at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.waitUntil(SeleniumHelper.java:888)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitUntilImpl(BrowserTest.java:1901)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitUntilOrStop(BrowserTest.java:1849)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.invokedWrappedInWaitUntil(BrowserTest.java:118)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.invoke(BrowserTest.java:84)
 at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:31)
 at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:221)
 at fitnesse.slim.fixtureInteraction.DefaultInteraction.callMethod(DefaultInteraction.java:204)
 at fitnesse.slim.fixtureInteraction.DefaultInteraction.invokeMethod(DefaultInteraction.java:188)
 at fitnesse.slim.fixtureInteraction.DefaultInteraction.findAndInvoke(DefaultInteraction.java:166)
 at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18)
 at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18)
 at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139)
 at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112)
 at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
 at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29)
 at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
 at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
 at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85)
 at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82)
 at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75)
 at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62)
 at fitnesse.slim.SlimServer.serve(SlimServer.java:47)
 at fitnesse.slim.SlimService.handle(SlimService.java:168)
 at fitnesse.slim.SlimService.acceptOne(SlimService.java:176)
 at fitnesse.slim.SlimService.accept(SlimService.java:138)
 at fitnesse.slim.SlimService.startWithFactory(SlimService.java:91)
 at fitnesse.slim.SlimService.main(SlimService.java:56)`

**Comment by fhoeben** [comment]
I've found some references to (older) chrome bugs that caused this error message. But these should be fixed with the chromedriver in this project.
Can you give some more information on the page you are experiencing this one, and your test?

For instance:
 * I believe your page contains frames, or iframes. Is that correct?
 * I believe you are not using `wait for visible <place> in <context>` (but just `wait for visible <place>`). Is that correct?
 * Do you use `set search context <context>` in your test?

If you are indeed testing a page with frames: could you see whether the errors disappear when you disable automatic searching in frames (using `|set implicit find in frames to| false|`) and explicitly switch to the frame you want to have something appear (using `|switch to frame|<technical selector>|`) ?

**Comment by Eddie1802** [comment]
You've visited us (Keylane) recently so you might know what we use better than me. 

We have newer pages based on Angular an older pages on JSP. I believe the errors occur on the Angular pages but didn't check.
We do not use frames or iframes in our own code althought there might be external plugins we use (like wysiwyg editors) that use them. But those or not on the pages currently under test.

We do override getElement(String place) to add heuristics specific for our application.

**Comment by fhoeben** [comment]
From the stack trace you sent me I can tell there must be (i)frames, since you hit line 46 in `TryAllFramesConditionDecorator.invokeInFrames()` :-)

Does the problem persist with the latest chromedriver (included in release 3.15.1)?

**Comment by Eddie1802** [comment]
The problem is still there with 15.1 although it seems less frequent. Confirmed that we do not use frames or iframes on the pages under test.

**Comment by Eddie1802** [comment]
I did some debugging on TryAllFramesConditionDecorator.invokeInFrames(). This method is reached on each of our Angular pages.
Most of the times the expression 
'List<WebElement> frames = webDriver.findElements(ConstantBy.frames());' 
returns frames size = 0 and we exit the method.

But on some runs (so not on every run) on pages where I've seen the error the frames size = 1 .
The statement 'this.helper.switchToFrame(frame);' triggers a 'org.openqa.selenium.StaleElementReferenceException' exception.

**Comment by fhoeben** [comment]
That sounds like the 'sometimes' is a frame, that also disappears again. But this issue (the stack trace you posted) is not for a org.openqa.selenium.StaleElementReferenceException, but for a (more generic) org.openqa.selenium.WebDriverException.

As you are sure that you don't need any contents from (i)frames in your tests you can disable checking in frames by `|set implicit find in frames to| false|`

**Comment by Eddie1802** [comment]
> As you are sure that you don't need any contents from (i)frames in your tests you can disable checking in frames by |set implicit find in frames to| false|

That helped on some pages but not all. The error seems to be introduced in the new version of chromedriver. Unfortunately the geckodriver has the same bug.

Is the new chromedriver version required for 3.15.1? Or could we downgrade to chromedriver 2.33?

**Comment by fhoeben** [comment]
I believe you should be able to downgrade (if you have a version of chrome still supported by the old driver).
