### ISSUE TITLE
Any reason selectFor() does not use Selenium's Select interface?

### ISSUE THREAD

**Issue by JessefSpecialisterren** [fhoeben/hsac-fitnesse-fixtures#220]
Yesterday, we ran into an issue where a \<select\> element with a very large amount of options would not work with `|select|...|for|...|`. It kept scrolling to the bottom of the page and giving exceptions about the element being obscured. On further investigation today, it turned out that altering BrowserTest's `clickSelectOption()` to use [Selenium's Select interface](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/ui/Select.html) solved this issue.

This makes me wonder: is there a reason why BrowserTest's `clickSelectOption()` does not use Selenium's Select interface? The current solution seems hacky in comparison. Is it perhaps left over from the time `|select|...|for|...|` still supported radio buttons?

At any rate, I'd be happy to create a PR to make it use Selenium's Select interface, if that seems like a good idea.

**Comment by fhoeben** [comment]
If I recall correctly I recently removed usage of Selenium's select helper :-)
But that was for 'value of', I believe, as Selenium's select was EXTREMELY slow for large lists.

Let me see whether I can find the commit.

**Comment by fhoeben** [comment]
It indeed was for retrieving values:
https://github.com/fhoeben/hsac-fitnesse-fixtures/commit/f6fb4d0fd05cfc8a3ab2f08e739817ed718319d0

A PR to select values in large lists is welcome (please do also supply an acceptance tests that shows the improved behaviour)

**Comment by JessefSpecialisterren** [comment]
After some more investigation, it turns out that this bug only occurs in Firefox and requires some very specific circumstances to be triggered. It seems to have something to do with the click trying to scroll to the \<option\> element, but I'm not entirely sure.

I made an acceptance test that triggers the bug, have a look at https://gist.github.com/JessefSpecialisterren/52157ad92044012d227c853ce2532a99. Add it under HsacAcceptanceTests.SlimTests.BrowserTest, be sure to start Firefox instead of Chrome in SuiteSetUp, and you should get the exception mentioned. It may be browser size dependent, but should occur at least on 1366x768.

I wonder what you make of it! Perhaps the bug could also be fixed by scrolling to the \<select\> element if it's not in view and then clicking the \<option\> without calling `scrollIfNotOnScreen(element);`.

**Comment by fhoeben** [comment]
I finally got round to trying your page. It indeed poses a problem for firefox (and not for chrome).
The problem unfortunately does not go away when I use Selenium's Select helper. I still get a the same error (`org.openqa.selenium.ElementClickInterceptedException: Element <select> is not clickable at point (36.17500305175781,923.75) because another element <div> obscures it`).


The problem does not seem to relate to scrolling (as the error is not with the scroll, but with the actual click on the option, which Selenium's Select also uses).


So I don't know how to address this problem. I suggest you file a bug report with the gecko driver project (which is Firefox's Selenium driver).


<img width="1132" alt="screen shot 2018-08-11 at 08 05 03" src="https://user-images.githubusercontent.com/5467859/43988816-97ad9312-9d3d-11e8-90a2-a9c4c3d736bb.png">

**Comment by JessefSpecialisterren** [comment]
Finally had time to further investigate this issue, and it turns out that the problem is in scrolling after all. Namely, the following strategy does work:

1. Scroll the _select_ element into view so that it's clickable (i.e. not obscured)
2. Click the option _without attempting to scroll to it_ (e.g. by just calling `.click()` on it instead of using `clickElement`)

As far as I can piece together, a combination of the following behaviors causes the problems in Firefox:

- HSAC attempts to scroll to the _option element_ if it's not on screen before clicking it (`clickSelectOption` calls `clickElement` on the option, which calls `doIfInteractable`, which calls `scrollIfNotOnScreen`)
- In Firefox, options can have a position above or below the select element, as can be seen when mousing over them in the developer toolbar: 
![Firefox option position](https://user-images.githubusercontent.com/36038882/46287536-265fcb80-c583-11e8-8c65-2f81e52a52c5.png)
The more options a select has, the further below (or above) the select the options can be
- In several browsers (at least Firefox and Chrome AFAIK), to be able to click an option, the _select element_ has to be on screen

So, when using Firefox, the `scrollIfNotOnScreen` to the _option_ element that HSAC performs may scroll the _select_ element into 1) being obscured behind an element with position:fixed or 2) being out of view. In case 1, the click of the option element will fail immediately. In case 2, however, when trying to click the option element, the select element is scrolled back into view as specified in the [webdriver spec](https://www.w3.org/TR/webdriver/#element-click) ("Scroll into view the element’s container"). This scrolling is [specified to be to "end" for block elements](https://www.w3.org/TR/webdriver/#dfn-scrolls-into-view), so if there is a position:fixed element at the bottom of the viewport, it is likely to obscure the select element and cause the click to fail.

The acceptance test in my previous comment triggers case 2. I made one that triggers case 1 over here: https://gist.githubusercontent.com/JessefSpecialisterren/84530e7003a93cb1bc107f21ef024ad1/raw/c38221f98d74b3a51e2923f05956422983930514/SelectCase1.wiki

We actually ran into this bug about five times in different projects over the past few months, so even though it requires specific circumstances, those are less rare than one might think.

My suggestion would be to alter HSAC to scroll to the _select element_ instead of the _option element_ and then click the option element without attempting to scroll. This is closer to the webdriver spec than the current implementation, and should work for all browsers (though I would of course thoroughly test that before submitting a PR 🙂). What do you think?
